permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "GreenGardens"
  description: |
    A small gardening business, with a good variation of small plants to large deluxe gardens for anyone's home.

patternbot:
  layouts:
    default: |
      The default layout should be used for every page, it includes the website's primary header and footer.
  font_url: "http://fonts.googleapis.com/css?family=Cabin:400,400i,700|Playfair+Display:400,700"
  colors:
    background: "--color-secondary-light"
    accent: "--color-neutral-dark"
    patterns:
      brand.logos: "--color-accent"
  rationales:
    typefaces.primary:  |
      Raleway is the primary typeface that i selected because i wanted to have a unique and clean serif type for the typeface. Raleway will be used throughout the website.
    colors.primary: |
      I wanted a neutral but earthy feel for the primary colour.
    colors.secondary:  |
      The secondary colour is a dark green-blue I wanted a colour for the type that could resemble the colours of succulents. And the white is for text that should be placed on darker backgrounds. Most of the text will be in these colours.

collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
