title: "Sections"
description: |
  A different type of navigation. Breadcrumbs through your website and the style of section used for bigger amounts of text.

patterns:
  breadcrumbs:
    title: "Breadcrumbs"
    description: |
      This is a navigation bar that should be used only to direct you on what order you visited the pages through the website.
  sections:
    title: "Sections"
    description: |
      These types of sections will be used only for sections that require more text. For less text you can look in the Cards section of this Pattern Library and find a banner if there's less text and a direction for the user to follow.
  side-navigation:
    title: "Side Navigation"
    description: |
      This navigation is not to be used as the main navigation. It could be used as a secondary navigation for less popular or less important pages of the website.
  divider:
    fields:
      - name: title
        type: string
        example: "Original Gardens"
