title: "Sections"
description: |
  Sections are made for all the big pieces of contents on your website.

patterns:
  breadcrumbs:
    title: "Breadcrumbs"
    description: |
      This is a navigation bar that should be used only to direct you on what order you visited the pages through the website.
  sections:
    title: "Sections"
    description: |
      This pattern will be used only for sections that require more text. For less text you can look in the Cards category of this Pattern Library and find a banner if there's less text and a direction for the user to follow.
  side-navigation:
    title: "Side Navigation"
    description: |
      This navigation is not to be used as the main navigation. It is made to be used as the navigation for the products page only. To easily filter through the different categories on the products page.
