title: "Forms"
description: |
  Forms should be used when purchasing an item and information is required for the purchase.

patterns:
  confirmation:
    fields:
      - name: text
        type: string
        example: "I agree with the information above"
    title: "Confirmation"
    description: |
      This pattern is a checkbox to be used with the button only at the end of the form to confirm all the information entered is correct.
  input:
    fields:
      - name: text
        type: string
        example: "Name"
    title: "Input"
    description: |
      This pattern is for when a form needs to be typed out with information.
  provinces:
    fields:
      - name: text
        type: string
        example: "Provinces"
      - name: option_1
        type: string
        example: "Select One"
      - name: option_2
        type: string
        example: "Alberta"
      - name: option_3
        type: string
        example: "British Columbia"
      - name: option_4
        type: string
        example: "Manitoba"
      - name: option_5
        type: string
        example: "New Brunswick"
      - name: option_6
        type: string
        example: "Newfoundland & Labrador"
      - name: option_7
        type: string
        example: "Northwest Territories"
      - name: option_8
        type: string
        example: "Nova Scotia"
      - name: option_9
        type: string
        example: "Nunavut"
      - name: option_10
        type: string
        example: "Ontario"
      - name: option_11
        type: string
        example: "Prince Edward Island"
      - name: option_12
        type: string
        example: "Quebec"
      - name: option_13
        type: string
        example: "Saskatchewan"
      - name: option_14
        type: string
        example: "Yukon"
    title: "Provinces"
    description: |
      Only use this pattern when there are multiple options to choose from.
  phone:
    fields:
      - name: text
        type: string
        example: "Phone"
    title: "Phone"
    description: |
      This pattern is to be used only for phone numbers.
  textarea:
    fields:
      - name: text
        type: string
        example: "Write a message"
    title: "Text Area"
    description: |
      This pattern is only the be used when you need to fill out the box with a lot of information.
  email:
    title: "Email"
    fields:
      - name: text
        type: string
        example: "Email"
    description: |
      This pattern is to be used only for emails.
