title: "Cards"
description: |
  Cards are to be used as a section on a page or to direct the user to another page.

patterns:
  basic-card:
    fields:
      - name: heading
        type: string
        example: "Explore our gardens!"
      - name: text
        type: string
        example: "Find a plant or garden that best suits your home and lifestyle. We garantee that you will find one that you love."
    title: "Basic Card"
    description: |
      This basic card is only to be used on top of a banner. If you want a card sitting on top of your banner instead of having plain text on top.
  call-to-action-banner:
    fields:
      - name: heading
        type: string
        example: "Explore our gardens!"
      - name: text
        type: string
        example: "Find a plant or garden that best suits your home and lifestyle. We garantee that you will find one that you love."
      - name: image
        type: string
        example: call-to-action-banner1.jpg
    title: "Call to Action Banner"
    description: |
      This banner should only be used on the top of your newsletter page below the main navigation and the promotion alert.
  image-card:
    fields:
      - name: heading
        type: string
        example: "Zebra Succulent"
      - name: text
        type: string
        example: "Smallest boxed succulent to make this item a piece of decor. Called the zebra succulent because of it's unique pattern on the leaves."
      - name: image
        type: string
        example: smallgarden4.jpg
    title: "Image Card"
    description: |
      This type of card is to be used to showcase products and direct the users to the shop page.
  product-card:
    title: "Product Card"
    description: |
      This card is to be used on the products page or newsletter page.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  sectional-banner:
    title: "Sectional Banner"
    description: |
      This sectional banner is only to be used when no action is required. Nothing on this banner should be changed. You can add this banner on any page as a section to a page.
  top-page-banner:
    fields:
      - name: heading
        type: string
        example: "Learn more about us"
      - name: text
        type: string
        example: "Discover more about us and our amazing plants!"
      - name: image
        type: string
        example: top-banner.jpg
    title: "Top Page Banner"
    description: |
      This banner is to be used on top of the products page below the main navigation.
  home-banner:
    fields:
      - name: heading
        type: string
        example: "Explore our gardens!"
      - name: text
        type: string
        example: "Find a plant or garden that best suits your home and lifestyle. We garantee that you will find one you love."
      - name: image
        type: string
        example: home-banner1.jpg
    title: "Home Banner"
    description: |
      This banner should only be used on at the top of your home page below the  main navigation.
