patterns:
  basic-card:
    fields:
      - name: heading
        type: string
        example: "Explore our gardens!"
      - name: text
        type: string
        example: "Find a plant or garden that best suits your home and lifestyle. We garantee that you will find one that you love."
    title: "Basic Card"
    description: |
      This basic card is only to be used on top of a banner. If you want a card sitting on top of your banner.
  call-to-action-banner:
    fields:
      - name: heading
        type: string
        example: "Explore our gardens!"
      - name: text
        type: string
        example: "Find a plant or garden that best suits your home and lifestyle. We garantee that you will find one that you love."
      - name: image
        type: string
        example: home-banner.jpg
    title: "Call to Action Banner"
    description: |
      This banner should be used as a sectional banner or a top of the page banner, but only if you need to direct the user to another page you would use this banner.
  image-card:
    fields:
      - name: heading
        type: string
        example: "Zebra Succulent"
      - name: text
        type: string
        example: "Smallest boxed succulent to make this item a piece of decor. Called the zebra succulent because of it's unique pattern on the leaves."
      - name: image
        type: string
        example: smallgarden4.jpg
    title: "Image Card"
    description: |
      This type of card is to be used to showcase products and direct the users to the shop page.
  product-card:
    title: "Product Card"
    description: |
      This card is to be used on the products page.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  sectional-banner:
    title: "Sectional Banner"
    description: |
      This sectional banner is only to be used when no action is required. Nothing on this banner should be changed. You can add this banner on either the home page or products page.
  top-page-banner:
    fields:
      - name: heading
        type: string
        example: "Learn more about us"
      - name: text
        type: string
        example: "Want to know what greengardens is all about? Discover more about us and our amazing plants!"
      - name: image
        type: string
        example: home-banner.jpg
    title: "Top Page Banner"
    description: |
      This is another variation of a call-to-action banner.
