patterns:
  promotion-alert:
    fields:
      - name: title
        type: string
        example: "Buy a premium garden and get one 50% off!"
    title: "Promotional Alert"
    description: |
      Only to be put at the top of the newsletter page below the navigation.
  pricing-table:
    title: "Pricing Table"
    description: |
      Only to be used on the newsletter page to showcase variaties of prices.
  newsletter-signup:
    fields:
      - name: text
        type: string
        example: " "
    title: "Newsletter Sign up"
    description: |
      To only be used one the newsletter page.
